// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Angular_Project.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Description { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Image { get; set; }

    [Column(TypeName = "decimal(7, 2)")]
    public decimal? Price { get; set; }

    public int? Quantity { get; set; }
}